version: "3.9"

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
